Error in .as.roman(x, check.range = TRUE) : object 'z' not found
Calls: prov.run ... withCallingHandlers -> eval -> eval -> as.roman -> .as.roman
Execution halted
